Feature/add evaluator
BenjaminDecaillet/M05-mp-decaillet pull request #17
Opened 2023-02-22 10:00 UTC by BenjaminDecaillet

Adding skeleton for evaluator class and it's unit tests

2023-02-22 10:21 UTC, decaillet requested changes

2023-02-22 10:21 UTC, decaillet commented on unit_tests/test_evaluator.py
> +from src.evaluator import Evaluator
That's not the proper way of managing imports in python.

look at the example in class Service

2023-02-22 10:50 UTC, BenjaminDecaillet commented on unit_tests/test_evaluator.py
> +from src.evaluator import Evaluator
I updated the code to be the way it is in service

2023-02-22 13:17 UTC, decaillet approved these changes

2023-02-22 13:18 UTC, merged

2023-02-24 17:21 UTC, decaillet commented
I have been bricoling... Now merged at 72ddf16d90d39399ac2ce006c2d3775dd56518e5