Feature/data preparator
BenjaminDecaillet/M05-mp-decaillet pull request #28
Opened 2023-03-03 13:05 UTC by BenjaminDecaillet

Adding 4 preparators to load dataset.
wine: load both red and white data and concatenate them in 1 dataset
white-wine: load white wines data
red-wine: load red wines data
boston: load boston houses

Each preparator first check to get the data from url in config file and if it fails get it from locally saved file

2023-03-04 22:20 UTC, decaillet requested changes
ok, j'ai encore 2 trucs "généraux" à redire #raleur

1. le dossier "extra", ça serait pas plus logique de l'appeler "data"?
  a) ce dossier contient des fichiers que tu as téléchargé "à la main" -> C'est une opération manuelle: il manque un ficher info.md qui explique où et quand tu les as téléchargé
  b) ou alors on part sur les fichiers locaux et distants _doivent_ être les mêmes, et on a un teste qui le vérifie (donc contrairement à ce que j'ai mis comme commentaire dans ton unit test, on ne mock _pas_ les appels réseau, et on teste que le load local et le load url ont donné le même dataframe...

2. un "dataset", traditionnellement, ça contient des "features" et des "targets"... Là, tu retournes que 1 seul dataframe; on en voudrait pas plutôt 2? (Et oui, ça implique qu'il faut savoir quelles sont les collones features et target - c'est, à mon avis, aussi le job du data preparator...


Sinon, remarque général: y a aussi plein de trucs qui _vont bien_ dans ton code (et que j'ai pas relevé.... Donc oui, y a des choses qui vont pas et qu'il va falloir refaire, mais tout n'est pas à jeter, loin de là

Bon taff et on en reparle lundi!

2023-03-04 22:20 UTC, decaillet commented on main.py
> +# classes
wtf?

(respectueusement et avec amour de ton cousin chéri, hein... Mais wtf quand-même ;)

2023-03-04 22:20 UTC, decaillet commented on src/__init__.py
> +from .preparator import Preparator
non.
Là t'es en train de faire un alias entre "Preparator" et "preparator.Perparator". On fait pas ça.
ta class Preparator est déjà déclarée dans le init du sous-dossier, ça suffit...

2023-03-04 22:20 UTC, decaillet commented on src/config.ini
> +bostonHouses = extra/housing.data
Je suis pas fan de ce design avec fichier 'ini'

En gros, un fichier de config (ini, .env, etc...) généralement c'est un fichier qui _change_ d'un déploiement à l'autre. Du coup, souvent, on versionne pas le fichier lui-même, mais 1 ou plusieurs exemples.
Ici, c'est pas le use-case: ces URLs vont jamais changer, du coup, on n'a pas de raison de les mettre dans une config. ça peut très bien être des constantes déclarées qqpart dans le code (typiquement, des constantes de classes privées dans la classe qui s'en sert...)

On en parle lundi si tu veux...

2023-03-04 22:20 UTC, decaillet commented on src/evaluator.py
> +    def __init__(self, preprocessor: Preprocessor, preparator: Preparator, file: str = '', url: str = ''):
Retirer `file`et `url`, je pense: ces choses-là devraient être _dans_ l'objet `preparator`: c'est à ça qu'il sert: il doit déjà savoir quoi préparer et comment faire (à quel file ou quelle url se fier...)

Ensuite, conseil de code-style général: si tu es en train d'appeller une variable `file` ou `url`, c'est souvent que t'es en train de faire un truc faux: c'est le fichier de quoi? L'url de quoi?

2023-03-04 22:20 UTC, decaillet commented on src/evaluator.py
> +
#pinaille: j'ai pas compris l'intérêt de la ligne vide ici...

2023-03-04 22:20 UTC, decaillet commented on src/preparator/factory.py
> +        if type not in {"wine", "white-wine", "red-wine", "boston"}:
j'ai pas assez regardé le use-case, je dis peut-être une connerie...

Pourquoi on a un design avec des types multiples pour les vins? Plutot que un type "wine" et un 2e paramètres "wine_type" in [red, white, both] ?

Il me semble que ça resssmble à la factoy de preprocessor, avec "polynomial" qui prend plusieurs "polynomial_kwargs" ?

Peut-être on en parle lundi?

2023-03-04 22:20 UTC, decaillet commented on src/preparator/redwine_preparator.py
> +            data = pd.read_csv(file, sep=';')
Yes! Bien joué, pandas!
C'était exactement ce qui fallait faire 👍

2023-03-04 22:20 UTC, decaillet commented on src/preparator/whitewine_preparator.py
> +class WhiteWinePreparator(Preparator):
ça pourrait pas un peu se DRYer avec le red wine, ça ?

2023-03-04 22:20 UTC, decaillet commented on src/preparator/wine_preparator.py
> +from src.preparator import Preparator, PreparatorFactory
Pourquoi tu importes `PreparatorFactory` ?

2023-03-04 22:20 UTC, decaillet commented on unit_tests/preparator/test_boston_preparator.py
> +        actual = preparator.load_data()
ça, ça appelle vraiment l'URL... Dans un unit test, c'est bad practice: en principe, on mock/patch les appels réseau.
Je dis pas que ça m'est jamais arrivé d'appeller une API dans un vrai projet, mais là, vu que c'est pour l'exercice, faudrait le mocker

2023-03-04 22:20 UTC, decaillet commented on src/preparator/boston_preparator.py
> +        try:
Attends, j'ai compris juste: on essaie d'appeler l'URL, et seulement si elle ne répond pas, on prend le fichier en local? C'est vraiment ce qu'on veut faire?
je pensais plutot:
- quand l'objet est créé, on lui dit s'il doit aller sur l'url ou sur le fichier local
- quand on lui dit load, il va chercher ce qu'on lui a dit d'aller chercher...

2023-03-04 22:20 UTC, decaillet commented on src/service.py
>          self._preprocessor_factory = src.preprocessing.PreprocessorFactory("standard")
`config_file`est unused

2023-03-06 06:47 UTC, BenjaminDecaillet commented on src/evaluator.py
> +    def __init__(self, preprocessor: Preprocessor, preparator: Preparator, file: str = '', url: str = ''):
Oui c'est un relicat mal nettoyé de mes premiers tests qui disparaît plus tard. My bad

2023-03-07 22:53 UTC, decaillet requested changes
J'arrête là la review pcq je pense que la  branch feature/data-preparator est de toute façon beaucoup trop grosse.

Je te propose de partir sur une nouvelle feature branch, plus petite: feature/load-boston-data:
- 1e commit, les données de boston (seulement boston)
- 2e commti, le boston_preparator tout seul
   - pas de factory,
   - pas de contract,
   - pas de test juste un pragma et un todo qui dit que tu feras après
   - pas configurable: ça load toujours les données du csv (pas d'url)
   - en pratique, tu vas reprendre pas mal de code de branch feature-data-formatter
   - MAIS, tu connectes ça dans le service, et quand on roule main.py, ça doit utiliser les données
- 3e commit: tu enlèves le pragma, et tu testes ta classe.

Et c'est tout. La suite, ce sera dans une (ou plusieurs) autre(s) branche(s)

2023-03-07 22:53 UTC, decaillet commented on src/evaluator.py
> +        _ = self._preparator.load_data()
Remplacer le _prepare_data (ci-dessous)!
Sinon, en pratique, on n'utiliser pas les données que tu extraits

2023-03-07 22:53 UTC, decaillet commented on src/preparator/base_preparator.py
> +        self._sep = files_kwargs['sep']
T'as pas besoin de tous ces membres. Tu stockes juste self._read_csv_kwargs, et tu les passe tous d'un coup après. (si c'est pas clair comment, appelle)

2023-03-07 22:53 UTC, decaillet commented on src/preparator/base_preparator.py
> +        self.data = pd.DataFrame()
Au lieu de `self.data`, on pourrait avoir une variable locale `data_tout_court` dans load_data, non?

2023-03-07 22:53 UTC, decaillet commented on src/preparator/base_preparator.py
> +            try:
Pas sûr que y ait besoin de gérer les exceptions ici...
Si y a pas les données, laisse remonter l'exception, on gérera dans service... ou fuck it on gère pas.

2023-03-07 22:53 UTC, decaillet commented on src/preparator/base_preparator.py
> +                if (self._delim_whitespace):
Je comprends pas pourquoi tu fais ça?

Je pense qu'on n'a pas besoin de ce if si on passe tous les kwargs en une seule fois...

2023-03-08 13:34 UTC, closed without merging

2023-03-08 13:35 UTC, BenjaminDecaillet commented
dismissed to more correct git commits line