Feature/licensing
BenjaminDecaillet/M05-mp-decaillet pull request #56
Opened 2023-03-20 10:04 UTC by BenjaminDecaillet

2023-03-20 15:52 UTC, BenjaminDecaillet commented
J'ai utilisé l'outil mentionné pour généré les licenses des package utilisés dans un format Json.

Je pense que c'est un point qu'on peut aborder à la prochaine VC de comment les gérer mais au moins maintenant elles sont là

2023-03-20 15:56 UTC, decaillet requested changes

2023-03-20 15:56 UTC, decaillet commented on LICENSE
> +Permission is hereby granted, free of charge, to any person obtaining a copy of this
Anglais bizarre... T'as coupé au milieu de la phrase la license d'avant. C'est fait exprès?

2023-03-20 15:56 UTC, decaillet commented on LICENSES
On n'a pas de détail sur comment cette license est générée. (je devine que c'est le tool à André, mais c'est pas écrit)
On peut l'inclure dans la doc?
Voire générer ce fichier depuis la doc?

2023-03-20 15:57 UTC, decaillet commented on LICENSES
Et aussi, faut rebase sur dev...

2023-03-22 17:27 UTC, BenjaminDecaillet commented on LICENSE
> +Permission is hereby granted, free of charge, to any person obtaining a copy of this
J'ai repris la phrase 👍

2023-03-22 17:27 UTC, BenjaminDecaillet commented on LICENSES
J'ai refait le licensing avec le fichier "licensing.md" qui explique comment générer, ajouter les fichiers générés dans le gitignore

2023-03-27 13:23 UTC, decaillet approved these changes

2023-03-27 13:26 UTC, merged